sudo: required
dist: trusty
install:
  - sudo apt-get update
  - sudo apt-get install python3-crypto
before_script:
  - git clone git://git.gnome.org/libsecret.git
script:
  - dbus-launch --exit-with-session /usr/bin/python2 tests/run_tests.py libsecret/libsecret/mock-service-normal.py
  - dbus-launch --exit-with-session /usr/bin/python3 tests/run_tests.py libsecret/libsecret/mock-service-normal.py
  - dbus-launch --exit-with-session /usr/bin/python2 tests/run_tests.py libsecret/libsecret/mock-service-only-plain.py
  - dbus-launch --exit-with-session /usr/bin/python3 tests/run_tests.py libsecret/libsecret/mock-service-only-plain.py
